name: ESLint

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint
          npm install @stylistic/eslint-plugin
          npm install @microsoft/eslint-formatter-sarif

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . --config eslint.config.js --ext .js --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: false

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

