name: HTML Validation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "Max/automate-validator" ]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'    

    - name: Install HTML validator
      run: npm install -g html-validator-cli

    - name: Validate HTML files with W3C
      run: |
        echo "🔍 Starting HTML validation..."
        has_errors=false
        
        for file in $(find . -name "*.html"); do
          echo "========================================================"
          echo "📄 Validating $file..."

          output=$(html-validator --file=$file --format=text --verbose --no-stream) || true
          
          if echo "$output" | grep -q "The document validates according to"; then
            echo "✅ $file is valid HTML"
          else
            echo "❌ $file has validation errors:"
            echo "$output"
            has_errors=true
          fi
          echo "========================================================"
        done
        
        if [ "$has_errors" = true ]; then
          echo "⚠️ Some HTML files have validation errors. Please fix them."
        else
          echo "✅ All HTML files are valid!"
        fi